# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json

blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/5rrxEUN
    about: Join our Discord server for anything else.
